### PR TITLE
[WIP] Add default trip creator

### LINKED ISSUE #33: Default implementation for trips creation
The current trips creation is very much custom for Florianópolis. This issue here is the place to discuss how a default implementation for trips creation could and should look like. Probably it's going to be in the direction of @jamescr Incofer trips creation, as he is using a standard json containing schedule information for all stops. Fenix and Managua is doing more fancy and custom stuff to create a schedule, which the can live (partially) in the respective individual creators.

### LINKED ISSUE #62: Format for departure/arrival times
My local company [Expresso Lorenzutti](http://www.expressolorenzutti.com.br/horarios.html) have made time tables available in PDF format. I understand it might be difficult to accommodate all forms of publishing time tables, and have therefor started to write a scraper for this. I would like to save it in a simple, common format, that osm2gtfs can read directly. One easy solution would be to save it as JSON. If you have any suggestions to formats I am open.

### PR DESCRIPTION
**Pull request by AltNico**
Based on Incofer's trip creator I filled the default trip creator with
life and orientated me while doing this at @Skippern's time.json
discussed in #33.

To do:
* Don't work

Fixes #33.
Fixes #62.

### CODE REVIEW

**Comment by AltNico** [comment]
I have added a wiki page containing information of the `timetable.json` which I'm implementing in this pull request. It's mostly based on the format of the discussion in #62 but I modified some tiny things to align well with the newly introduced data structure of #70 and to be more clear. @Skippern @xamanu As you both plan to use that format, do you mind reading the wiki page whether everything is fine?

**Comment by xamanu** [comment]
I suggest closing this PR and file a new pull request based on the recent work (which has been already successfully used to generate GTFS in Nicaragua): https://github.com/mapanica/osm2gtfs/tree/default-creators

**Comment by AltNico** [comment]
@xamanu
> I suggest closing this PR and file a new pull request based on the recent work, which has been already successfully used by us to generate GTFSes in Nicaragua: https://github.com/mapanica/osm2gtfs/tree/default-creators

I agree with you!

**Comment by answerquest** [comment]
hey what happened?

**Comment by ValorNaram** [comment]
For others who came here and wondered about the dead link in @AltNico's last message.

A working link is https://github.com/mapanica/easy-timetable-generator (they just changed the name of their repo)

**Pull request closed without merging**
