### PR TITLE
Accra creator

### PR DESCRIPTION
**Pull request by nlehuby**
* GTFS routes are created with OSM route_master relations
* GTFS Trips are created by frequency, using a `frequency` tag on route_master relations
* OSM route relations are used to enrich GTFS trips (direction_id, headsign)
* Stop areas are created (by name and distance)

TODO : 
- [x] use real data for GTFS frequency opening hours
- [x] use real data for trip travel time

### CODE REVIEW

**Comment by grote** [comment]
Wow that was fast! I am currently traveling, but looks like there's still two TODOs open anyway.

Before I can look into this in detail, maybe check out the default stop creator implementation in another PR. Maybe it can be re-used/merged with yours. There's also one for stop areas (grouping stops).
For the trip creator, we maybe can move the interpolation method into the default `TripsCreator` class to reduce code duplication wherever possible.

**Comment by nlehuby** [comment]
Thanks for your feedback.
You can have a look at the generated GTFS, the TODOs are mocks to be removed soon.

About the `TripCreator`, I've modified the default creator, and refactor the 3 creators accordingly.

About the `StopCreator`, we are not sure about the correct way to handle it accordingly to your vision : 
* you can create GTFS stops without any grouping (current default creator, seems a fine default behaviour)
* you can group GTFS stops using OSM StopArea (PR #55 )
* you can group GTFS stops by name and proximity (current PR, Accra creator)
* you can mix it all (using OSM Stop Area and grouping them by name and proximity)
Feel free to have a chat with @prhod in Paris in September about this.

Enjoy your vacations ;)

**Comment by prhod** [comment]
We talked about this PR with @grote, and ended with : 
* A default generation using OSM StopArea only
* A second method that can use both (OSM StopArea and if not available, using distance and/or name)

The name use can be irrelevant in Brazil, because each StopPoint may have unique name (using street names with house numbers).

**Comment by nlehuby** [comment]
As there is no StopArea in Accra I will stick to the name + distance method in this PR.
Maybe you should make an issue so that we have all theses details somewhere when we will refactor the default stop creator ?

**Comment by grote** [comment]
> As there is no StopArea in Accra I will stick to the name + distance method in this PR.

Sure that makes sense!

> Maybe you should make an issue so that we have all theses details somewhere when we will refactor the default stop creator ?

What do you mean exactly?

The idea discussed with @prhod in Paris was to let the default creator use stop area relations, since this is the OSM approach. But then provide another StopCreator that works based on distance. This one doesn't need to live inside the AccraCreator as it is useful for other regions such as Brazil as well. Ideally, it inherits from the other creator or a common super class to reduce code duplication.

**Comment by prhod** [comment]
What @nlehuby is saying is that this PR is about the Accra GTFS generator. This PR shouldn't be blocked by the global enhancement of osm2gtfs with the StopArea default creator we mentioned. 
Would you agree on this steps : 
* creating an issue about the StopArea default creator (I can do it if you're ok with it)
* merging this PR to make this accra generator "official" (with possible enhancements later)
* working on the StopArea default creator afterward, with possible refacto on existing gtfs creators

**Comment by grote** [comment]
I didn't mean to say that this PR is blocked by the stop creator discussion. Do you consider it ready to be reviewed and merged?

> working on the StopArea default creator afterward

Do you mean to say that you want this to be merged before #65 or will it work either way?

**Comment by nlehuby** [comment]
This PR is ready to be reviewed. 

As Accra does not use the stop default creator, the PRs are supposed to be independent, and may be merged in any order.

**Comment by jamescr** [comment]
I agree everything under accra folder is independent, but we should encourage to use as much as possible the default creators.

@nlehuby a couple of doubts:

Do you have a link to OSM wiki or documentation about the default usage of `frequency` and `travel_time` tags? I think the usage is very straightforward but is better to have a documentation at hand (just in case). 

The `frequency` tag should not be a param of route instead of route_master?

**Comment by nlehuby** [comment]
`frequency` and `travel_time` are not standard tags for now, so they do not have a wiki page.
Do you want me to add a link [to the Accra project](https://wiki.openstreetmap.org/wiki/AccraMobile3#Tro_tro_line) ? Or to add explanation about the tags in a comment ? 

The `frequency` could have been on the route just as the `travel_time` tag. But as it is an approximate value of the frequency of the lines, it would have been duplicated on both routes by the contributors.

**Comment by jamescr** [comment]
> frequency and travel_time are not standard tags for now, so they do not have a wiki page.
Do you want me to add a link to the Accra project ? Or to add explanation about the tags in a comment ?

Maybe the wiki is a great place for that info. (see issue #12)

>The frequency could have been on the route just as the travel_time tag. But as it is an approximate value of the frequency of the lines, it would have been duplicated on both routes by the contributors.

I think `frequency` is better in the `routes` (variants) than in the route master. Because the value is not associated to the master, i mean two routes could be related in a route_master but each route with different frequency.

**Comment by prhod** [comment]
For the `frequency` matter, in some cases you are right : the `frequency` is different from a variation to an other. On the other hand, there are some lines (I think for example of long distance `coach`) that don't need variations, and the `frequency` of the forward and backward routes should be the same. Why not setting this property to the `route_master` ?
Speaking of which, a frequency could  also vary on the time of the day ... :-p
Personally, I think both locations are correct, depending on the accuracy expected.

**Comment by jamescr** [comment]
Well, `frequency` on both `route_master` and `route` is OK for me.

**Comment by grote** [comment]
Just to let you know that for osm2gtfs and this MR, I personally don't care how you structure the data within OSM.

**Comment by grote** [comment]
> As Accra does not use the stop default creator, the PRs are supposed to be independent, and may be merged in any order.

`StopsCreatorAccra` is inheriting from the `StopsCreator` though.

> Well, frequency on both route_master and route is OK for me.

What does it mean then if both have a different frequency?

**Comment by jamescr** [comment]
>> Well, frequency on both route_master and route is OK for me.
>What does it mean then if both have a different frequency?

For me, route variant frequency has priority.

**Comment by grote** [comment]
> For me, route variant frequency has priority.

Sounds reasonable, but should be explicitly defined somewhere.

@nlehuby this now has merge conflicts with master.

**Comment by nlehuby** [comment]
rebase ok

**Pull request merged**
