### PR TITLE
Unit tests coverage for data objects

### PR DESCRIPTION
**Pull request by jcfausto**
Added some unit test coverage to the core/osm_routes.py module. Currently 63% of coverage. 

This is a contribution to the issue #75 done during the #hacktoberfest

### CODE REVIEW

**Comment by jcfausto** [comment]
Okay. Need to fix some pep8 and pylint issues first. Please wait for that fixes before evaluating this pull request. :-)

**Comment by grote** [comment]
Hi @jcfausto, thanks a lot for your first PR!

Unfortunately, after merging #79 this now has conflicts. Would you mind rebasing on `master`?

**Comment by jcfausto** [comment]
Hi @grote, sure, no problem. I'll do that.

**Comment by jcfausto** [comment]
Done @grote :-)

**Comment by grote** [comment]
Strange is that GitHub shows me 7 commits in this MR and even changes in the diff that were already applied. I waited some days thinking it would go away, but it didn't.

**Comment by jcfausto** [comment]
Ok. I'm not sure also why the logs messed up.
 
Maybe we can close this PR, as rejected, and I can do another one based on current Master. This way we won't have any issues when merging. The changes I did are easy to redo, they'll not take too much time. 

What do you think?

**Comment by grote** [comment]
Normally, you should be able to simply rebase this on latest master. I tried, but get merge conflicts I am too lazy to resolve now.

    git fetch origin
    git rebase -i origin/master

**Comment by grote** [comment]
@prhod as you already did the other unit tests, do you want to try and rebase this one?

**Comment by xamanu** [comment]
I gave it a [try](https://github.com/xamanu/osm2gtfs/tree/elements-test), rebased on PR #99. It is still work in progress. But in case @prhod or anybody else wants to look into this, maybe it helps a bit.

**Comment by grote** [comment]
@xamanu do you just want to open a new one based on your work? Looks like this one isn't progressing anywhere.

**Comment by xamanu** [comment]
Sure, however I prefer to wait until the other open pull requests go in (one contains already some tests) and then properly rebase the work I've done and go step by step with small and easy reviewable pull requests to cover the core.

**Pull request closed without merging**
