### PR TITLE
Improved package and module names (#37 and #38)

### PR DESCRIPTION
**Pull request by xamanu**
Let's keep PR small again :smile:

- Using PEP8 compliant module names for creators and factory (#37)
- Merged modules `osmhelper` and `factory` to `core` (#38)
- Minor edits in the README file

However cached data needs to be refreshed anyway.

Cheers and thanks.

### CODE REVIEW

**Comment by xamanu** [comment]
I further included a small change to the caching. Now it actually uses the `selector` from the config in the file name for pickle-caches. This allows to work on different cities without rewriting the cache every time.

**Comment by xamanu** [comment]
And, another additional (minor) thing: Fixed some error handling in `OsmConnector` about missing reference numbers in data.

**Comment by grote** [comment]
Wow! Thanks for the next PR so fast!

When running `--refresh-all` I get this:
```
Traceback (most recent call last):
  File "./osm2gtfs.py", line 111, in <module>
    main()
  File "./osm2gtfs.py", line 64, in main
    data.get_routes(refresh=True)
  File "./osm2gtfs/core/osm_connector.py", line 127, in get_routes
    rv = result.get_relations(member.ref).pop()
IndexError: pop from empty list
```

**Comment by xamanu** [comment]
Error fixed. Sorry this `pop()` had to happen after checking if there are actually results.

**Pull request merged**
