### PR TITLE
Introduce python logging module

### PR DESCRIPTION
**Pull request by xamanu**
This is a PR related to issue #46 - Improve debugging by introducing python's [logging](https://docs.python.org/2/library/logging.html) module.

### CODE REVIEW

**Comment by nlehuby** [comment]
There are still a few `print` that could be changed to logging messages in the following files:
* core/osm_connector.py
* creators/trips_creator.py

**Comment by xamanu** [comment]
Thanks! Transformed the `print` into `logging.info` and rebased the PR on latest master.

**Comment by xamanu** [comment]
It had again a little conflict after the latest PR has been accepted. Rebased again.

**Comment by grote** [comment]
Do you have any idea why the CI is failing on this branch only?

**Comment by xamanu** [comment]
No. I basically just rebased. Looks a bit like a strange error.

**Comment by grote** [comment]
Could it be that the tests run a long time and now there's no more output where there was output before?

**Comment by xamanu** [comment]
Yes, indeed. The logging level was not being set properly when running the tests, and fell back to the standard `WARNING`, which was not giving that regular output. Now, for tests the logging level `INFO` is set, too, and tests run successfully \o/

**Pull request merged**
